// Copyright 2017-2021 @polkadot/phishing authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/phishing', version: '0.6.121' };
