// Copyright 2017-2024 @polkadot/phishing authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/phishing', path: 'auto', type: 'auto', version: '0.24.4-11-x' };
