// Copyright 2017-2023 @polkadot/phishing authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/phishing', path: 'auto', type: 'auto', version: '0.21.6-275-x' };
